# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, unique=True)),
                ('watched', models.IntegerField(default=1)),
                ('watched_full', models.BooleanField(default=True)),
                ('rating', models.IntegerField()),
                ('source', models.CharField(max_length=500, null=True)),
                ('imdb_rating', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_type', models.CharField(choices=[('Act', 'Action'), ('Ani', 'Animation'), ('Com', 'Comedy'), ('Doc', 'Documentary'), ('Fam', 'Family'), ('FN', 'Film-Noir'), ('Hor', 'Horror'), ('Mus', 'Musical'), ('Rom', 'Romance'), ('Spo', 'Sport'), ('War', 'War'), ('Adv', 'Adventure'), ('Bio', 'Biography'), ('Cri', 'Crime'), ('Dra', 'Drama'), ('Fan', 'Fantasy'), ('His', 'History'), ('Mus', 'Music'), ('Mys', 'Mystery'), ('Sci', 'Sci-Fi'), ('Thr', 'Thriller'), ('Western', 'Western')], max_length=3)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='WatchTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
    ]
