# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiren',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_full', models.BooleanField(default=True)),
                ('rating', models.IntegerField()),
                ('source', models.CharField(max_length=500, null=True)),
                ('watched_at', models.DateField()),
                ('video_quality', models.CharField(choices=[('HD', 'HD'), ('Cam', 'Cam'), ('Dvd', 'DVD'), ('480', '480'), ('720', '720'), ('108', '1080')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='watchtime',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='source',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched_full',
        ),
        migrations.DeleteModel(
            name='WatchTime',
        ),
        migrations.AddField(
            model_name='hiren',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
