# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20161115_1957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='watched',
            new_name='number_of_times_watched',
        ),
        migrations.AddField(
            model_name='hiren',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiren',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
