# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20161116_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movietype',
            name='movie',
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_type',
            field=models.CharField(choices=[('Act', 'Action'), ('Ani', 'Animation'), ('Com', 'Comedy'), ('Doc', 'Documentary'), ('Fam', 'Family'), ('FN', 'Film-Noir'), ('Hor', 'Horror'), ('Mus', 'Musical'), ('Rom', 'Romance'), ('Spo', 'Sport'), ('War', 'War'), ('Adv', 'Adventure'), ('Bio', 'Biography'), ('Cri', 'Crime'), ('Dra', 'Drama'), ('Fan', 'Fantasy'), ('His', 'History'), ('Mus', 'Music'), ('Mys', 'Mystery'), ('Sci', 'Sci-Fi'), ('Thr', 'Thriller'), ('Wes', 'Western')], default='Com', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='MovieType',
        ),
    ]
