# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_auto_20161116_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=800),
        ),
    ]
