# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20161208_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=800, unique=True),
        ),
    ]
